version: "3"

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: myapp_development
      TZ: Asia/Tokyo
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root -p password
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s

  api:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: bash -c "rm -f /myapp/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/myapp
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy

  front:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    ports:
      - "4000:3000"
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "cd app && yarn && yarn start"

volumes:
  db-data:
  public-data:
  tmp-data:
  log-data:
